---
title: "Convolution in R"
format: 
  html:
    code-link: false
    header-includes:
      - <link rel="preconnect" href="https://fonts.googleapis.com">
      - <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      - <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;600;700&display=swap" rel="stylesheet">
    
engine: knitr
filters:
 - webr
---

```{css, echo=FALSE}
.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    z-index: 2;
    color: #fff;
    background-color: #7AB629;
    border-color: #337ab7;
}
a:link,
a:visited,
a:hover{
  color: #7AB629;
}
/* Aktiver TOC-Link  */
#TOC a.active,
#TOC .active > a {
  color: #fff !important;
  background-color: #7AB629 !important;
}


/* Hover im TOC */
#TOC a:hover {
  color: #7AB629 !important;
}

:root, body {
  font-family: "Mulish", system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
}

.quarto-code-links {
  display: none !important;
}
```

```{webr-r}

#| context: setup

# Download a dataset
download.file(
  'https://raw.githubusercontent.com/DaChro/aohrsi_tutorials/main/data/convolution_example.tif',
  'convolution_example.tif'
)
webr::install("terra")

```

*Course "Analysis of high-resolution remote sensing imagery"* - **Institute for Geoinformatics - University of Muenster** - christian.knoth\@uni-muenster.de

------------------------------------------------------------------------

## Introduction

R is a language and environment for statistical computing with loads of functionality for handling and processing spatial data. It plays a large role in (spatial) data science and remote sensing, because it is open source, it is easily extensible, and it is used a lot by non-computer programmers to carry out programming tasks. R is freely available at [r-project.org](http://www.r-project.org/). A very useful software to help work with R is [Rstudio](http://www.rstudio.org). Rstudio is a comprehensive development and data analysis environment, that extends R with a GUI and lots of helpful tools and functions. It can be used instead of R's own, rather rudimentary user interface. First install R, then install RStudio. The latter automatically connects to the existing R connection (but you need both, R and Rstudio).

For those of you who have never worked with R before: this document is not an introduction to R (there are tons of introductions and tutorials available). Instead, this document is designed in a way such that you can simply copy paste the code line by line to conduct spatial convolution in R, and then simply replace the coefficients of the kernels and other convolution parameters to create different filters and inspect the results

## Preparation

### Set working directory

As a first step, you should create a directory on your computer, in which you store the data and scripts for this exercise. Then set this directory as your working directory for this R session. The working directory is the folder in which R by default stores data or where it looks for data if no full file path is provided (if you set your working directory correctly, you can later load and save data without always specifying full paths but only use file names). You can set your working directory in R studio through the menu: Choose "Session", then "Set Working Directory", then "Choose Directory".

You can also use the command `setwd("path to directory in qoutes")`.

### Install and load required packages

Next, we need to extend our base R with additional functionality. For the following exercise, we will use the `terra` package for handling remote sensing images (and other raster data) and performing spatial convolutions. A package in R is kind of an extension providing additional functionality that is not available in the base R installation. As of now, there are almost 19000(!) packages available on [CRAN](https://cran.r-project.org/), which is R´s standard package repository. To install a package, you can either use the "Packages" pane in the lower right window (click on "Install" and search for the desired package) in Rstudio or simply use the `install.packages()` command:

```{r, eval=F}
install.packages("terra")
```

Now you have downloaded the package. But it is not yet ready to use. The reason is that additional packages are not automatically "loaded" into an R session. Remember there are many thousands of packages available and every user usually has quite a lot of them installed. Automatically loading them for each session would unnecessarily blow up the software. This is why you simply load the functions of a package in your R session only when needed. To load the `terra` package in our R session, we can again use the "Packages" pane in the lower right window (It shows all installed packages and you can load the desired package by checking the box next to it) or simply use the `library()` command.

```{webr-r}
library(terra) # please note that here you do not use quotation marks
```

*Note: If you work on your script multiple times, you only need to do `install.packages()` once. `library()` on the other hand needs to be done in each session, because this loads the package for the currently running session (see above)*

## Load data

Now that we have prepared our session, we can load the example image using the \`rast\`\` function:

```{webr-r}
input_image <- rast("convolution_example.tif") # note that here we only specify the file name, assuming that this file is in the folder that we specified as working directory
```

We have now loaded the example image into our R session and assigned it to the variable `input_image` (by using the `<-` operator). From now on, we can "access" the image by typing its variable `input_image`. To get an idea of of what you have loaded, simply type in the variable:

```{webr-r inspect}
input_image
```

You get some information about the image, e.g., size, number of layers(bands), CRS, min and max values ...

To plot the image, you can use the `plotRGB()` function with the image as argument (more precisely, the variable holding the image):

```{webr-r}
plotRGB(x=input_image)
```

*side note: Why `x=input_image` you ask? Because `x` is the name of the argument that is expected by the function `plotRGB()` to indicate which raster to plot, in our case the raster contained in `input_image`. If you check the help of this function (`?plotRGB`), you get information about the usage of it, e.g., which input arguments it expects and how they are called. You will find some other useful arguments for plotting remote sensing images such `r`, `g`, `b` (for defining which of the layers contains which color) or `stretch` (for applying a contrast stretch to the image when plotting). Here however, we only specify the raster to plot, which means that the default values will be used for all other arguments.*

## Spatial Convolution

For performing spatial convolution. We can use the `focal()` function of the `terra` package. This function requires as main inputs the raster layer we want convolve (argument `x`) and a matrix to use as filter kernel (argument `w`) . So before applying `focal`, let´s define the filter kernel. As you know from the lecture, the kernel is a matrix of coefficients. We can create matrices using the function `matrix()`

```{webr-r filter matrix}
kernel <- matrix(c(1,1,1,1,1,1,1,1,1),nrow = 3,byrow = T)
kernel
```

As you can tell from the output, we have defined the kernel for a spatial moving average like the one you have seen in the lecture. The first argument for the `matrix()` function here is a vector of numbers that we want to fill the matrix (our kernel) with, i.e. our coefficients. We defined it by typing `c(1,1,1,1,1,1,1,1,1)`.

*side note: Please note, that since all coefficients are the same, there would be a shorter form to define them: `rep(1,9)`which basically means "repeat the number 1 nine times", so the following does the same thing.*

```{webr-r filter matrix2}
kernel <- matrix(rep(1,9),nrow = 3,byrow = T)
kernel
```

*The first version `c(1,1,1,1,1,1,1,1,1)` is chosen here for clarity, and because you can also use it for other filters with varying coefficients.*

The argument `nrow = 3` specifies the number of rows our matrix should have. There is also an argument `ncol` but we don´t need to set it, because R infers the number of columns from the number of elements provided to fill the matrix and the desired number of rows. Setting either `ncol` or `nrow` is enough. The argument `byrow=T` defines the order in which to fill the matrix with the elements, so in this case by row. It means that the numbers `c(1,1,1,1,1,1,1,1,1)` are filled in the matrix starting with the first row, then continuing with the second and so on. If we would not set this argument, R would use the default `byrow=FALSE`, which means it would fill the matrix by column. This would result in the same matrix in this case, but this can be different when you have other coefficients or other forms of matrices. So just keep in mind to use the correct ordering of coefficient in combination with the correct setting of `byrow` to end up with the filter kernel you actually want.

Now that we have defined our filter kernel and loaded the image, we can apply the filter to one channel (band) of that image. A specific channel (band) of an image is selected using double brackets, e.g. `input_image[[1]]` for choosing layer 1.

```{webr-r filter focal mean}
sma <- focal(x = input_image[[1]], w = kernel,fun=mean)
```

Here we have applied the function `focal()` on the layer 1 of the image `input_image` using the kernel/matrix called `kernel`. As you can see, we have also set an argument `fun`. This defines the function to apply to the products resulting from multiplying all the coefficients in the kernel `w` with the corresponding pixel values in the image `x`. By default (if we don´t set `fun`) the function will simply apply `sum`, i.e. sum up all the products. In the lecture we have defined most of the filters with the mean, i.e. we divided the sum of all products by the number of coefficients. To do that with `focal`, we can simply set `fun=mean` so the mean of all products is being computed. Another way to get the same results would be to stick with `sum` (i.e., do not set the argument `fun`) and include the division by 9 directly in the filter kernel by defining the coefficients accordingly with `c(1/9,1/9,1/9,1/9,1/9,1/9,1/9,1/9,1/9)` or `rep(1/9,9)`.

We can plot the result by:

```{webr-r plot result}
plot(x=sma, col=grey(1:255/255))
```

And we can save it (e.g. to open and inspect it in QGIS) via:

```{webr-r save result}
writeRaster(x=sma,file="sma.tif", overwrite = T)
```

Instead of the moving average, we could also apply the median without having to change anything about the kernel. We simply use `fun=median` in the function `focal`.

```{webr-r focal median}
my_median_filter <- focal(x = input_image[[1]], w = kernel,fun=median)
writeRaster(my_median_filter,"median.tif", overwrite = T)
```

## Exercise

Using the code snippets above, try out different filter configurations and inspect their results on the input image. For inspecting the results, export them (`writeRaster`, see above) and open them in QGIS:

1.  Apply a standard deviation filter with a 3x3 kernel. Check the result on the pixel level: are the pixel values identical to what you would expect given the calculation rules shown in the lecture?

2.  Apply the moving average, median and standard deviation filters above with a different filter kernel size and check the impact on the result.

3.  Jensen (2016) provides a list with some selected filters (see learnweb). Apply some of them and inspect the results.

4.  Implement the Sobel operator by choosing appropriate filter coefficients and a suitable `fun` argument and compare the result with the sobel operator from OTB in QGIS.

    *Hint: you can first compute the X and Y component with the corresponding filters, and then combine them using the equation given in the lecture. The command for calculating the square root is `sqrt()`. Squaring works with `^2`, so for squaring thev alues of a raster use `raster^2`.*

5.  Apply the Sobel operator to enhance only horizontal and only vertical edges individually and inspect the results.

6.  The `focal()`function also provides the optional arguments `pad` and `padValue`. Using the help `?focal()` and thinking back to the lecture, find out what they are for, how to use them and how they would influence the result.
